library(shiny)
library(bslib)
library(shinyjs)
library(shinyWidgets)
library(DT)
library(tidyr)
library(dplyr)
library(readr)
library(stringr)
library(readxl)
library(openxlsx)
library(ggplot2)
library(plotly)
# library(ComplexHeatmap)
library(enviPat)
library(markdown)

options(shiny.maxRequestSize = 100 * 1024^2)

source("helpers.R")
source("aggregate/module.R")
source("preprocessing/module.R")
source("visualization/module.R")
helpers_script <- list.files("visualization/helpers", pattern = "\\.R$", full.names = TRUE)
lapply(helpers_script, source)
plot_module <- list.files("visualization/types-modules", pattern = "\\.R$", full.names = TRUE)
lapply(plot_module, source)
vs_types <- tools::file_path_sans_ext(list.files("visualization/types-modules", pattern = "\\.R$"))
source("tf/module.R")
source("enviPat/module.R")
source("md5check/module.R")
