library(shiny)
library(DT)
library(shinyjs)
library(bslib)
library(shinyWidgets)
library(dplyr)
library(tidyr)
library(stringr)
library(readr)
library(readxl)
library(openxlsx)
library(ggplot2)
library(plotly)
# library(ComplexHeatmap)
library(enviPat)
library(markdown)

options(shiny.maxRequestSize = 100 * 1024^2)

source("helpers.R")
source("data-science/aggregate/module.R")
source("data-science/visualization/module.R")
helpers_script <- list.files("data-science/visualization/helpers", pattern = "\\.R$", full.names = TRUE)
lapply(helpers_script, source)
types_modules <- list.files("data-science/visualization/types-modules", pattern = "\\.R$", full.names = TRUE)
lapply(types_modules, source)
vs_types <- tools::file_path_sans_ext(list.files("data-science/visualization/types-modules", pattern = "\\.R$"))
source("omics/data-preprocessing/module.R")
source("mass-tools/enviPat/module.R")
source("mass-tools/tf/module.R")
source("toolkits/md5check/module.R")