library(shiny)
library(DT)
library(shinyjs)
library(bslib)
library(shinyWidgets)
library(dplyr)
library(tibble)
library(purrr)
library(forcats)
library(stringr)
library(tidyr)
library(readr)
library(readxl)
library(openxlsx)
library(ggplot2)
library(plotly)
# library(ComplexHeatmap)
library(enviPat)
library(markdown)
library(broom)  # tidy()

options(shiny.maxRequestSize = 100 * 1024^2)

source("helpers.R")
source("data-science/aggregate/module-aggr.R")
source("data-science/statistics/module-stat.R")
stat_modules <- list.files("data-science/statistics/stat-modules/", pattern = "\\.R$", full.names = TRUE)
lapply(stat_modules, source)
stat_types <- tools::file_path_sans_ext(list.files("data-science/statistics/stat-modules", pattern = "\\.R$"))
source("data-science/visualization/module-vs.R")
helpers_script <- list.files("data-science/visualization/helpers", pattern = "\\.R$", full.names = TRUE)
lapply(helpers_script, source)
vs_modules <- list.files("data-science/visualization/vs-modules", pattern = "\\.R$", full.names = TRUE)
lapply(vs_modules, source)
vs_types <- tools::file_path_sans_ext(list.files("data-science/visualization/vs-modules", pattern = "\\.R$"))
source("omics/data-preprocessing/module-pp.R")
source("mass-tools/enviPat/module-enviPat.R")
source("mass-tools/tf/module-tf.R")
source("toolkits/md5check/module-md5check.R")